In [2]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([[1, 1], [1, 1]])
C = A + B
print(C)

[[2 3]
 [4 5]]


In [3]:
A = np.array([[1, 2], [3, 4], [5, 6]])
B = np.array([[2, 3], [2, 3]])
C = np.matmul(A, B)
print(C)

[[ 6  9]
 [14 21]
 [22 33]]


In [4]:
A = np.array([[1, 2], [3, 4]])
k = 10
C = k * A
print(C)

[[10 20]
 [30 40]]


In [5]:
import pandas as pd

# 인덱스를 생략한 시리즈 객체
numbers = pd.Series([100, 200, 300])

# 시리즈 객체 출력
print(numbers)

# 인덱스를 지정한 시리즈 객체
scores = pd.Series([90, 80, 99], index=['국어', '수학', '영어'])

# 시리즈 객체 출력
print(scores)

# 시리즈 객체의 인덱스 출력
print(scores.index)

# 시리즈 객체의 데이터값 출력
print(scores.values)

# 원하는 위치의 인덱스, 데이터값 출력
print(scores.index[1], scores.values[1])

0    100
1    200
2    300
dtype: int64
국어    90
수학    80
영어    99
dtype: int64
Index(['국어', '수학', '영어'], dtype='object')
[90 80 99]
수학 80


In [7]:
import pandas as pd

# 계절별 서울/부산 지역 온도 데이터 정의
temperatures = [[3.3, 34.5, 14.2, -10], [7.1, 32.1, 10.7, 2]]
seasons = ['Spring', 'Summer', 'Fall', 'Winter']
regions = ['Seoul', 'Pusan']

# 데이터프레임 객체 생성
data = pd.DataFrame(temperatures, index=regions, columns=seasons)

# 데이터프레임 객체의 데이터 출력
print(data)
print("=" * 50) # 구분선
print(data.index)
print(data.columns)
print(data.values)
print("=" * 50)

# 서울의 봄 온도 데이터 출력
print(data['Spring']['Seoul'])
print("=" * 50)

# 앞부분에서 2번쨰 행까지 조회
print(data.head(2))
print("=" * 50) # 구분선

# 뒷부분에서 1번째 행까지 조회
print(data.tail(1))

       Spring  Summer  Fall  Winter
Seoul     3.3    34.5  14.2     -10
Pusan     7.1    32.1  10.7       2
Index(['Seoul', 'Pusan'], dtype='object')
Index(['Spring', 'Summer', 'Fall', 'Winter'], dtype='object')
[[  3.3  34.5  14.2 -10. ]
 [  7.1  32.1  10.7   2. ]]
3.3
       Spring  Summer  Fall  Winter
Seoul     3.3    34.5  14.2     -10
Pusan     7.1    32.1  10.7       2
       Spring  Summer  Fall  Winter
Pusan     7.1    32.1  10.7       2
